package main.Enums;

public enum Resource {
    CREDITS,
    STEEL,
    TITANIUM,
    PLANTS,
    ENERGY,
    HEAT,
    CREDIT_PRODUCTION,
    STEEL_PRODUCTION,
    TITANIUM_PRODUCTION,
    PLANT_PRODUCTION,
    ENERGY_PRODUCTION,
    HEAT_PRODUCTION,
    TERRAFORMING_RATING
}
